# Generated by Django 5.2.5 on 2025-08-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('housing', 'Housing'), ('insurance', 'Insurance'), ('medical', 'Medical'), ('food/supplies', 'Food & Supplies'), ('utilities', 'Utilities'), ('entertainment', 'Entertainemnt'), ('personal', 'Personal')], max_length=255),
        ),
    ]
