# Generated by Django 5.2.5 on 2025-08-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Insurance', 'Insurance'), ('Medical', 'Medical'), ('Food & supplies', 'Food & Supplies'), ('Utilities', 'Utilities'), ('Entertainment', 'Entertainemnt'), ('Personal', 'Personal')], max_length=255),
        ),
    ]
